Update routing.md
I got this error: 
faucet@ubuntu:~$ as_ns host2 ip route add default via 10.0.1.254 veth0
Error: either "to" is duplicate, or "veth0" is a garbage.
I think because this typo:
create_ns host1 10.0.0.254/24
create_ns host2 10.0.1.254/24
I make it 10.0.0.1/24 and 10.0.1.1/24
Then I tried it again, and it only works after I add dev to the command 

as_ns host1 ip route add default via 10.0.0.254 dev veth0
as_ns host2 ip route add default via 10.0.1.254 dev veth0

As you suggest reload is better than restart faucet. 

Location of sw1/2-faucet.yaml is not specified before. 
Maybe better to be $HOME